services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app_data:/app/data
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server local
    environment:
      - ENV_GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - kestra_data:/app/storage
      - kestra_db:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - "8080:8080"
volumes:
  app_data:
    name: cattle_raising_assistant_app_data
  kestra_data:
  kestra_db:
 
