"""LLM-as-a-judge evaluation for generated RAG answers.

Since there is no single "correct" text for a generated answer, quality is
scored by asking an LLM to judge it against the question and the context it
was allowed to use, on two axes: whether it actually answers the question
(relevance), and whether every claim in it is backed by the context
(groundedness, the axis that matters most for a veterinary-adjacent
assistant that must not invent health information).
"""

import json

from google.genai import types

from src.retrieval.vector_search import get_client

JUDGE_MODEL = "gemini-3.5-flash"

JUDGE_SCHEMA = {
    "type": "OBJECT",
    "properties": {
        "relevance": {
            "type": "STRING",
            "enum": ["RELEVANT", "PARTLY_RELEVANT", "NON_RELEVANT"],
        },
        "grounded": {"type": "BOOLEAN"},
        "explanation": {"type": "STRING"},
    },
    "required": ["relevance", "grounded", "explanation"],
}


def build_judge_prompt(question: str, context: str, answer: str) -> str:
    """Build the prompt that asks the judge model to score an answer."""
    return f"""You are evaluating an answer generated by a cattle-health RAG assistant.

Question: {question}

Context the assistant was allowed to use (nothing else):
{context}

Generated answer:
{answer}

Judge the answer on two axes:
- relevance: RELEVANT if it fully answers the question, PARTLY_RELEVANT if it \
answers part of it or is vague, NON_RELEVANT if it does not answer it.
- grounded: true only if every factual claim in the answer is supported by the \
context above. False if it invents or assumes information not present there.

Give a short explanation (one or two sentences) justifying both judgments.
"""


def judge_answer(question: str, context: str, answer: str) -> dict[str, str | bool]:
    """Score a generated answer for relevance and groundedness using an LLM judge."""
    client = get_client()
    response = client.models.generate_content(
        model=JUDGE_MODEL,
        contents=build_judge_prompt(question, context, answer),
        config=types.GenerateContentConfig(
            temperature=0,
            response_mime_type="application/json",
            response_schema=JUDGE_SCHEMA,
        ),
    )

    return json.loads(response.text)