import json

from src.generation.groq_client import get_groq_client

JUDGE_MODEL = "llama-3.3-70b-versatile"


def build_judge_prompt(question: str, context: str, answer: str) -> str:
    """Build the prompt that asks the judge model to score an answer.

    Groq's JSON mode guarantees syntactically valid JSON but does not
    enforce a schema (unlike Gemini's response_schema), so the exact key
    names and allowed values are spelled out explicitly here.
    """
    return f"""You are evaluating an answer generated by a cattle-health RAG assistant.

Question: {question}

Context the assistant was allowed to use (nothing else):
{context}

Generated answer:
{answer}

Judge the answer on two axes:
- relevance: RELEVANT if it fully answers the question, PARTLY_RELEVANT if it \
answers part of it or is vague, NON_RELEVANT if it does not answer it.
- grounded: true only if every factual claim in the answer is supported by the \
context above. False if it invents or assumes information not present there.

Respond with ONLY a JSON object (no markdown, no extra text) with exactly these keys:
{{
  "relevance": "RELEVANT" | "PARTLY_RELEVANT" | "NON_RELEVANT",
  "grounded": true | false,
  "explanation": "one or two sentences justifying both judgments"
}}
"""


def judge_answer(question: str, context: str, answer: str) -> dict[str, str | bool]:
    """Score a generated answer for relevance and groundedness using an LLM judge."""
    client = get_groq_client()
    response = client.chat.completions.create(
        model=JUDGE_MODEL,
        messages=[{"role": "user", "content": build_judge_prompt(question, context, answer)}],
        temperature=0,
        response_format={"type": "json_object"},
    )

    return json.loads(response.choices[0].message.content)